package com.weiboinfo.rsjBaseService.dto.ua;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 树节点的实体类
 * json tree node for jstree
 * 
 * @author fengwei // Expected format of the node (there are no required fields)
 *         { id : "string" // will be autogenerated if omitted text : "string"
 *         // node text icon : "string" // string for custom state : { opened :
 *         boolean // is the node open disabled : boolean // is the node
 *         disabled selected : boolean // is the node selected }, children : []
 *         // array of strings or objects li_attr : {} // attributes for the
 *         generated LI node a_attr : {} // attributes for the generated A node
 *         }
 *
 */
public class TreeNode implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -6301977663061562859L;
	private String id, text, icon;
	private TreeNodeState state = new TreeNodeState();
	private List<TreeNode> children = new ArrayList<TreeNode>();
	private Map<String, Object> attr;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public TreeNodeState getState() {
		return state;
	}

	public void setState(TreeNodeState state) {
		this.state = state;
	}

	public List<TreeNode> getChildren() {
		return children;
	}

	public void setChildren(List<TreeNode> children) {
		this.children = children;
	}

	public Map<String, Object> getAttr() {
		return attr;
	}

	public void setAttr(Map<String, Object> attr) {
		this.attr = attr;
	}

	public void putAttr(String key, Object value) {
		if (attr == null) {
			attr = new HashMap<String, Object>();
		}
		attr.put(key, value);
	}

	public void addChild(TreeNode node) {
		this.children.add(node);
	}

	public void setOpened(boolean opened) {
		this.state.opened = opened;
	}

	public void setDisabled(boolean disabled) {
		this.state.disabled = disabled;
	}

	public void setSelected(boolean selected) {
		this.state.selected = selected;
	}

	// 节点状态
	class TreeNodeState  implements Serializable{
		/**
		 * 
		 */
		private static final long serialVersionUID = 8788350373040758006L;
		private boolean opened = true;
		private boolean disabled = false;
		private boolean selected = false;

		public boolean isOpened() {
			return opened;
		}

		public void setOpened(boolean opened) {
			this.opened = opened;
		}

		public boolean isDisabled() {
			return disabled;
		}

		public void setDisabled(boolean disabled) {
			this.disabled = disabled;
		}

		public boolean isSelected() {
			return selected;
		}

		public void setSelected(boolean selected) {
			this.selected = selected;
		}
	}
}
